- hosts: all
  become: true
  vars_files:
    - cnc_values.yaml
  become_method: sudo
  tasks:

    - name: Check NVIDIA Driver Modules are loaded
      shell: "lsmod | grep -i nvidia"
      register: nvidia_mod
      no_log: True
      failed_when: false

    - name: Install NVIDIA TRD Driver
      become: true
      when:  nvidia_mod.rc == 1 and cnc_version <= 6.1
      block:
        - name: Get Apt Key
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
            dest: /tmp/3bf863cc.pub
            mode: 0664

        - name: Add NVIDIA Driver APT key
          shell: cat /tmp/3bf863cc.pub | apt-key add

        - name: Get OLD Apt Key
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
            dest: /tmp/7fa2af80.pub
            mode: 0664

        - name: Add OLD NVIDIA Driver APT key
          shell: cat /tmp/7fa2af80.pub | apt-key add

        - name: Install TRD Driver
          apt:
            deb: https://us.download.nvidia.com/tesla/510.47.03/nvidia-driver-local-repo-ubuntu2004-510.47.03_1.0-1_amd64.deb
            state: present
            update_cache: yes

        - name: Install NVIDIA CUDA Drivers
          ignore_errors: true
          apt:
            name: cuda-drivers
            update_cache: yes
            state: latest

    - name: Install NVIDIA TRD Driver
      become: true
      when:  cnc_version >= 6.2 and nvidia_mod.rc == 1
      block:
        - name: Install NVIDIA TRD Drivers
          ignore_errors: true
          apt:
            name: ['nvidia-driver-515', 'nvidia-dkms-515']
            update_cache: yes
            state: latest

    - name: Reboot the system
      when:  nvidia_mod.rc == 1
      reboot:
        reboot_timeout: 900
